### ISSUE TITLE
cumsum_kbn signature is too restrictive

### ISSUE THREAD

**Issue by stevengj** [JuliaMath/KahanSummation.jl#4]
The signature `cumsum_kbn(v::AbstractVector{T}) where T<:AbstractFloat` seems too restrictive.  What about summing `Complex{Float64}` or `SVector{Float64,3}`, for example?

`sum_kbn` accepts any type, which seems more reasonable.  (If you pass something like an array of integers, it will still work, just wasting some computations.)

**Comment by ararslan** [comment]
It also seems to assume 1-based indexing. Generalizing that to allow `OffsetArray`s would be nice as well.

**Comment by JeffreySarnoff** [comment]
OK -- revisiting.
What signature is recommended?
```
cumsum_kbn(v::AbstractVector)
cumsum_kbn(v::AbstractVector{T}) where {T<:Number}
etc
```

**Comment by JeffreySarnoff** [comment]
fixed in master
